RestClients:
  ThreemaGateway:
    UUID: af315689-b538-4142-a823-0632d66754d7
    Url: https://msgapi.threema.ch
    Icon: res:/webContent/icons/threema-icon_black.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
