Variables:
  threemaConnector:
   
    # Your Threema.Gateway ID 
    # [password]
    threemaId: ''
    
    # Your Threema.Gateway Secret
    # [password]
    secret: ''
    
    # Your private key associated with your Threema.Gateway ID
    # [password]
    privateKey: ''
