Variables:

  threema-connector:
    
    # Your Threema ID
    threemaId: ""

    # Secret from your Threema.Gateway Account
    secret: ""
    
    # Private key from your Threema.Gateway Account
    privateKey: "" 