# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  threemaConnector:
    
    # Your Threema.Gateway ID 
    threemaId: ''
    
    # Your Threema.Gateway Secret
    # [password]
    secret: ''
    
    # Your private key associated with your Threema.Gateway ID
    # [password]
    privateKey: ''
