name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dthreema.threemaId=${{secrets.THREEMA_ID}} -Dthreema.secret=${{secrets.SECRET}} -Dthreema.privateKey=${{secrets.PRIVATE_KEY}}