name: E2E-Build

on:
  schedule:
    - cron:  '0 1 * * 1'
  workflow_dispatch:
  
permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dthreema.threemaId=${{secrets.THREEMA_ID}} -Dthreema.secret=${{secrets.SECRET}} -Dthreema.privateKey=${{secrets.PRIVATE_KEY}} -DtestEnvironment=E2E